/********************************************************************************
 * Apex Class Name - TMProductStrategyVSUPG
 * Created Date - Jan 15, 2019
 * Modification Log : 
 * --------------------------------------------------------------------------------
 * Version   Developer       Date                    Description
 * ------    -----------     ------------            -----------------------
 * 1.0       Manuel          15/01/2019              Revise Version
 ********************************************************************************/
 
public class TMProductStrategyVSUPG extends TMProductStrategyVHIS{

    public TMProductStrategyVSUPG(TMPolicyUtil.PolicyTransactionValidationStruct ptvs){
        super(ptvs,'VSUPG');
    }

}