/********************************************************************************
 * Apex Class Name - TMProductStrategyVSPWG
 * Created Date - Dec 06, 2021
 * Modification Log : 
 * --------------------------------------------------------------------------------
 * Version   Developer       Date                    Description
 * ------    -----------     ------------            -----------------------
 * 1.0       Jinni          06/12/2021               Construction
 ********************************************************************************/
 
public class TMProductStrategyVSPWG extends TMProductStrategyVHIS{

    public TMProductStrategyVSPWG(TMPolicyUtil.PolicyTransactionValidationStruct ptvs){
        super(ptvs,'VSPWG');
    }

}